version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433" # HostPort:ContainerPort (changed host port to 14330)

  authenticationapi:
    build:
      context: .
      dockerfile: CarMarketplace.AuthenticationApiSolution/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__SharedSecret=your-very-secret-value
      - ConnectionStrings__AuthenticationConnectionString=Server=sqlserver;Database=AuthenticationServiceDB;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5000:8080"

  carlistingapi:
    build:
      context: .
      dockerfile: CarMarketplace.CarListingApiSolution/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__SharedSecret=your-very-secret-value
      - ConnectionStrings__CarListConnectionString=Server=sqlserver;Database=CarListingServiceDB;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5001:8080"

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__authCluster__Destinations__authApi__Address=http://authenticationapi:8080/
      - ReverseProxy__Clusters__carCluster__Destinations__carApi__Address=http://carlistingapi:8080/
    depends_on:
      - authenticationapi
      - carlistingapi
    ports:
      - "5002:8080"
